### ISSUE TITLE
API calls with special characters fail

### ISSUE THREAD

**Issue by cszhu** [cszhu/battledex#3]
Calls to the PokeAPI (https://github.com/PokeAPI/pokeapi/) fail when calling Pokemon like Farfetch'd (apostrophe) and Nine Tails (space). I think it has to do with how we are calling the API.

**Comment by matthino** [comment]
looks like the names in the DB are 'farfetchd' and 'ninetales'. check out: 
https://github.com/PokeAPI/pokeapi/blob/master/data/v2/csv/pokemon.csv

also, when did there become 812 pokemon???

**Comment by cszhu** [comment]
Thank you @matthino <3 I will just filter out the special characters when making the call :)

(I don't recognize the 300 more recent pokemon either lol)

**Comment by cszhu** [comment]
Fixed! 👍
