### ISSUE TITLE
height & weight are off

### ISSUE THREAD

**Issue by matthino** [cszhu/battledex#4]
Height and weight returned from PokeAPI calls should be divided by ten - or something along those lines.

for example the height and weight for Bulbasaur:
[**pokeAPI**](https://github.com/PokeAPI/pokeapi/blob/master/data/v2/csv/pokemon.csv) returns 7 and 69

[**bulbapedia**](http://bulbapedia.bulbagarden.net/wiki/Bulbasaur_%28Pok%C3%A9mon%29) claims 0.7m and 6.9kg

_extra bonus: adding measurement units (meters and kilograms) to display text_ (:

**Comment by cszhu** [comment]
Thanks!! I thought something seemed off but when I checked the PokeAPI they didn't really say what units they were in. I'll fix this ASAP 😃

**Comment by matthino** [comment]
Yeah, just something super small that caught my eye haha!

**Comment by cszhu** [comment]
Fixed! 👍
